import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import {ConfirmProvider} from "@/components/form/confirm";
import {TopLoader} from "@/components/ui/top-loader";
import { AppSidebar } from "@/components/layout/app-sidebar";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={'dark'}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <TopLoader/>
          <ConfirmProvider>
            <SidebarProvider>
              <AppSidebar />
              <SidebarInset>
                <main className="flex-1 overflow-auto p-4">
                  {children}
                </main>
              </SidebarInset>
            </SidebarProvider>
          </ConfirmProvider>
      </body>
    </html>
  );
}
